language: node_js

node_js:
  - 8
  - 10
  - 12
  - 13

jobs:
  include:
    - script: npm run lint
      name: Lint
      node_js: lts/*

deploy:
  provider: npm
  email: "harry.sarson@hotmail.co.uk"
  api_key: $NPM_TOKEN
  node_js: lts/*
  on:
    tags: true
